# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/natasablagojevic/ai/blob/main/09.Z3/1.ipynb
"""

# Z3 - resava probleme iz iskazne i predikatske logike, u logici u opste

from z3 import *

x, y, z = Reals('x y z')
s = Solver()
s.add(x > 1, y > 1, x+y > 3, z-x < 10)
s.check()

m = s.model()

print("x = ", m[x])
print("y = ", m[y])
print("z = ", m[z])

for d in m.decls():
    print(f'{d} = {m[d]}')

# Reals, Bools, Ints, Function

#                  domen      kodomen
f = Function('f', IntSort(), IntSort()) # f : Z -> Z
x,y = Ints('x y')
solve(f(f(x)) == x, f(x) == y, x != y)

# def solve(a):
#    s = Solver()
#    s.add(a)
#    if s.check() == sat:
#       print(s.model())

#                  domen      kodomen
f = Function('f', IntSort(), IntSort()) # f : Z -> Z
x,y = Ints('x y')
solve(f(f(x)) == x, f(x) == y, x != y)
print(s.check())
m = s.model()
m.evaluate(f(f(x)))